apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-api
  template:
    metadata:
      labels:
        app: poc-api
    spec:
      containers:
      - name: poc-api
        image: docker-k8s-poc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
